# Generated by Django 5.2.8 on 2026-08-06 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carton_no', models.CharField(help_text='e.g. CTN-001', max_length=32)),
                ('length_in', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='length (in)')),
                ('width_in', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='width (in)')),
                ('height_in', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='height (in)')),
                ('gross_weight_kg', models.DecimalField(blank=True, decimal_places=3, help_text='The whole sealed carton, as a courier would weigh it.', max_digits=10, null=True, verbose_name='gross weight (kg)')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('box_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.boxtype')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CartonContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit', models.CharField(choices=[('pcs', 'pcs'), ('set', 'set')], default='pcs', max_length=8)),
                ('net_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='net weight (kg)')),
                ('carton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='orders.carton')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carton_contents', to='catalog.productpart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carton_contents', to='catalog.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, help_text='e.g. HG-2026-0142', max_length=32, unique=True)),
                ('name', models.CharField(help_text='e.g. UO Fall Dining Refresh', max_length=180)),
                ('buyer_name', models.CharField(blank=True, max_length=120)),
                ('ship_country', models.CharField(default='US', max_length=2)),
                ('ship_line1', models.CharField(blank=True, max_length=180)),
                ('ship_line2', models.CharField(blank=True, max_length=180)),
                ('ship_city', models.CharField(blank=True, max_length=80)),
                ('ship_state', models.CharField(blank=True, max_length=80)),
                ('ship_postal_code', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('packing', 'Packing'), ('packed', 'Packed'), ('shipped', 'Shipped')], default='draft', max_length=10)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='masters.merchant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='carton',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartons', to='orders.order'),
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='catalog.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='carton',
            constraint=models.UniqueConstraint(fields=('order', 'carton_no'), name='unique_carton_no_per_order'),
        ),
        migrations.AddConstraint(
            model_name='orderline',
            constraint=models.UniqueConstraint(fields=('order', 'product'), name='one_line_per_product_per_order'),
        ),
    ]
