# Generated by Django 5.2.8 on 2026-08-07 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carton',
            name='box_type',
        ),
    ]
