# Generated by Django 5.2.8 on 2026-08-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_carton_box_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='color',
            field=models.CharField(blank=True, help_text='e.g. Natural Oak', max_length=60),
        ),
    ]
