# Generated by Django 5.2.8 on 2026-08-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_carton_no_box_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='rate_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Unit price on this order, in US dollars. The invoice multiplies it by what ships.', max_digits=12, null=True, verbose_name='rate (US$)'),
        ),
    ]
