# Generated by Django 5.2.8 on 2026-08-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoxType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='e.g. STD-M', max_length=32, unique=True)),
                ('name', models.CharField(help_text='e.g. Standard Medium', max_length=120)),
                ('length_in', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='length (in)')),
                ('width_in', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='width (in)')),
                ('height_in', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='height (in)')),
                ('max_weight_kg', models.DecimalField(blank=True, decimal_places=3, help_text='Optional. What this carton can safely carry.', max_digits=10, null=True, verbose_name='max weight (kg)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'box type',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='e.g. UO', max_length=16, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('country', models.CharField(blank=True, help_text='ISO code, e.g. US', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('remark', models.TextField(blank=True, help_text='Packing instruction for the group.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
