# Generated by Django 5.2.8 on 2026-08-07 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_product_box_type_remove_product_product_group_and_more'),
        ('masters', '0001_initial'),
        ('orders', '0002_remove_carton_box_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoxType',
        ),
        migrations.DeleteModel(
            name='ProductGroup',
        ),
    ]
