# Generated by Django 5.2.8 on 2026-08-12 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_delete_boxtype_delete_productgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text="The merchant's own store number", max_length=32)),
                ('name', models.CharField(max_length=180)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('ship_line1', models.CharField(blank=True, max_length=180)),
                ('ship_line2', models.CharField(blank=True, max_length=180)),
                ('ship_city', models.CharField(blank=True, max_length=80)),
                ('ship_state', models.CharField(blank=True, max_length=80)),
                ('ship_postal_code', models.CharField(blank=True, max_length=20)),
                ('ship_country', models.CharField(default='US', help_text='ISO code, e.g. US', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='masters.merchant')),
            ],
            options={
                'ordering': ['merchant__name', 'code'],
                'constraints': [models.UniqueConstraint(fields=('merchant', 'code'), name='unique_store_code_per_merchant')],
            },
        ),
    ]
