# Generated by Django 5.2.8 on 2026-08-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_store'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['code']},
        ),
        migrations.RemoveConstraint(
            model_name='store',
            name='unique_store_code_per_merchant',
        ),
        migrations.RemoveField(
            model_name='store',
            name='merchant',
        ),
        migrations.AlterField(
            model_name='store',
            name='code',
            field=models.CharField(help_text='Store number', max_length=32, unique=True),
        ),
    ]
