# Generated by Django 5.2.8 on 2026-08-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_make_stores_global'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='store',
            name='code',
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(help_text='Number and name, e.g. "118 Portland Pearl"', max_length=180, unique=True),
        ),
    ]
