# Generated by Django 5.2.8 on 2026-08-10 09:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0002_delete_boxtype_delete_productgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, help_text='e.g. DP-2026-0142', max_length=32, unique=True)),
                ('name', models.CharField(help_text='e.g. UO Winter Electronics', max_length=180)),
                ('buyer_name', models.CharField(blank=True, max_length=120)),
                ('ship_country', models.CharField(default='US', max_length=2)),
                ('ship_line1', models.CharField(blank=True, max_length=180)),
                ('ship_line2', models.CharField(blank=True, max_length=180)),
                ('ship_city', models.CharField(blank=True, max_length=80)),
                ('ship_state', models.CharField(blank=True, max_length=80)),
                ('ship_postal_code', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('packing', 'Packing'), ('packed', 'Packed'), ('shipped', 'Shipped')], default='draft', max_length=10)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='display_orders', to='masters.merchant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisplayCarton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carton_no', models.CharField(help_text='e.g. CTN-001', max_length=32)),
                ('length_in', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='length (in)')),
                ('width_in', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='width (in)')),
                ('height_in', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='height (in)')),
                ('box_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='box weight (kg)')),
                ('packing_material_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='packing material weight (kg)')),
                ('gross_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='gross weight (kg)')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartons', to='display.displayorder')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DisplayProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('style_no', models.CharField(help_text='Unique SKU code, e.g. DSP-WRT-24', max_length=64, unique=True)),
                ('description', models.CharField(help_text='e.g. 24" Pine Wreath', max_length=255)),
                ('customs_description', models.CharField(blank=True, max_length=255)),
                ('hsn_code', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('product_weight_kg', models.DecimalField(blank=True, decimal_places=3, help_text='The bare item with no packaging.', max_digits=10, null=True, verbose_name='product weight (kg)')),
                ('length_in', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='length (in)')),
                ('width_in', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='width (in)')),
                ('height_in', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='height (in)')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='display_products', to='masters.category')),
            ],
            options={
                'ordering': ['style_no'],
            },
        ),
        migrations.CreateModel(
            name='DisplayCartonContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit', models.CharField(choices=[('pcs', 'pcs'), ('set', 'set')], default='pcs', max_length=8)),
                ('net_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='net weight (kg)')),
                ('carton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='display.displaycarton')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carton_contents', to='display.displayproduct')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PackStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='display.displayorder')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.AddField(
            model_name='displaycarton',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartons', to='display.packstep'),
        ),
        migrations.CreateModel(
            name='PackTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='e.g. TPL-001', max_length=32, unique=True)),
                ('name', models.CharField(help_text='e.g. 30 bows + 5 wreaths', max_length=180)),
                ('remark', models.TextField(blank=True)),
                ('box_length_in', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='box length (in)')),
                ('box_width_in', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='box width (in)')),
                ('box_height_in', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='box height (in)')),
                ('box_weight_kg', models.DecimalField(blank=True, decimal_places=3, help_text='The empty carton on its own.', max_digits=10, null=True, verbose_name='box weight (kg)')),
                ('packing_material_weight_kg', models.DecimalField(blank=True, decimal_places=3, help_text='Padding and filler inside the box, not the box itself.', max_digits=10, null=True, verbose_name='packing material weight (kg)')),
                ('is_library', models.BooleanField(default=False, help_text='On = offer this template on later orders too.')),
                ('is_active', models.BooleanField(default=True)),
                ('merchant', models.ForeignKey(blank=True, help_text='Leave empty to offer this template on every order.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pack_templates', to='masters.merchant')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='packstep',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steps', to='display.packtemplate'),
        ),
        migrations.CreateModel(
            name='PackTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_items', to='display.displayproduct')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='display.packtemplate')),
            ],
            options={
                'verbose_name': 'item',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DisplayOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('color', models.CharField(blank=True, max_length=60)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='display.displayorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='display.displayproduct')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('order', 'product'), name='one_display_line_per_product_per_order')],
            },
        ),
        migrations.AddConstraint(
            model_name='displaycarton',
            constraint=models.UniqueConstraint(fields=('order', 'carton_no'), name='unique_display_carton_no_per_order'),
        ),
        migrations.AddConstraint(
            model_name='packstep',
            constraint=models.UniqueConstraint(fields=('order', 'sequence'), name='unique_step_sequence_per_order'),
        ),
        migrations.AddConstraint(
            model_name='packstep',
            constraint=models.CheckConstraint(condition=models.Q(('count__gte', 1)), name='step_count_positive'),
        ),
        migrations.AddConstraint(
            model_name='packtemplateitem',
            constraint=models.UniqueConstraint(fields=('template', 'product'), name='one_row_per_product_per_template'),
        ),
        migrations.AddConstraint(
            model_name='packtemplateitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='template_item_quantity_positive'),
        ),
    ]
