# Generated by Django 5.2.8 on 2026-08-10 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packtemplate',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Set on a one-off, so it is offered only on that order.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='own_templates', to='display.displayorder'),
        ),
    ]
