# Generated by Django 5.2.8 on 2026-08-11 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_packtemplate_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='displayproduct',
            name='is_multi_part',
            field=models.BooleanField(default=False, help_text='On = packs as separate parts, which may go in different templates.'),
        ),
        migrations.CreateModel(
            name='DisplayProductPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Wreath frame', max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('customs_description', models.CharField(blank=True, max_length=255)),
                ('hsn_code', models.CharField(blank=True, max_length=20)),
                ('product_weight_kg', models.DecimalField(blank=True, decimal_places=3, help_text='The bare part with no packaging.', max_digits=10, null=True, verbose_name='part weight (kg)')),
                ('length_in', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='part length (in)')),
                ('width_in', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='part width (in)')),
                ('height_in', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='part height (in)')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='display.displayproduct')),
            ],
            options={
                'verbose_name': 'part',
                'ordering': ['product', 'sort_order', 'id'],
            },
        ),
    ]
