# Generated by Django 5.2.8 on 2026-08-11 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_displayproduct_is_multi_part_displayproductpart'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='packtemplateitem',
            name='one_row_per_product_per_template',
        ),
        migrations.AddField(
            model_name='displaycartoncontent',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carton_contents', to='display.displayproductpart'),
        ),
        migrations.AddField(
            model_name='packtemplateitem',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='template_items', to='display.displayproductpart'),
        ),
        migrations.AddConstraint(
            model_name='packtemplateitem',
            constraint=models.UniqueConstraint(fields=('template', 'product', 'part'), name='one_row_per_piece_per_template', nulls_distinct=False),
        ),
    ]
