# Generated by Django 5.2.8 on 2026-08-13 09:02

import apps.display.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0008_step_and_carton_store_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='displayproduct',
            name='style_name',
            field=models.CharField(blank=True, help_text="The buyer's name for the style.", max_length=180),
        ),
        migrations.CreateModel(
            name='DisplayProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.display.models.display_product_image_path)),
                ('is_main', models.BooleanField(default=False, help_text='The one photo shown in lists and summaries.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='display.displayproductpart')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='display.displayproduct')),
            ],
            options={
                'ordering': ['-is_main', 'sort_order', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('part__isnull', True), ('product__isnull', False)), models.Q(('part__isnull', False), ('product__isnull', True)), _connector='OR'), name='display_image_belongs_to_exactly_one_owner')],
            },
        ),
    ]
