# Generated by Django 5.2.8 on 2026-08-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0009_product_images_and_style_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='displayorderline',
            options={'ordering': ['store__name', 'id']},
        ),
        migrations.AlterField(
            model_name='displayproduct',
            name='description',
            field=models.CharField(blank=True, help_text='e.g. 24" Pine Wreath', max_length=255),
        ),
    ]
