# Generated by Django 5.2.8 on 2026-08-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0010_alter_displayorderline_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packtemplate',
            name='code',
            field=models.CharField(blank=True, help_text='Left empty, it is assigned: BOX-001, BOX-002 …', max_length=32, unique=True),
        ),
    ]
