# Generated by Django 5.2.8 on 2026-08-19 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0012_carton_no_box_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayOrderRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_usd', models.DecimalField(decimal_places=2, help_text='Unit price on this order, in US dollars. The invoice multiplies it by what ships.', max_digits=12, verbose_name='rate (US$)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='display.displayorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_rates', to='display.displayproduct')),
            ],
            options={
                'ordering': ['product__style_no'],
                'constraints': [models.UniqueConstraint(fields=('order', 'product'), name='one_rate_per_product_per_order')],
            },
        ),
    ]
