# Generated by Django 5.2.8 on 2026-08-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0013_displayorderrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='displayproduct',
            name='is_delegate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='displayproductpart',
            name='is_delegate',
            field=models.BooleanField(default=False),
        ),
    ]
