# Generated by Django 5.2.8 on 2026-09-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0015_displayorderline_store_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='displayproduct',
            name='hts_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='displayproductpart',
            name='hts_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
