# Generated by Django 5.2.8 on 2026-09-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0016_hts_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='displayorder',
            name='export_details',
            field=models.JSONField(blank=True, default=dict, help_text='Customs/export header details (Invoice No, PO, Ports, Vessel, etc.)'),
        ),
    ]
