# Generated by Django 5.2.8 on 2026-08-06 11:08

import apps.catalog.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('box_length_in', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='box length (in)')),
                ('box_width_in', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='box width (in)')),
                ('box_height_in', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='box height (in)')),
                ('product_weight_kg', models.DecimalField(blank=True, decimal_places=3, help_text='The bare item with no packaging.', max_digits=10, null=True, verbose_name='product weight (kg)')),
                ('box_weight_kg', models.DecimalField(blank=True, decimal_places=3, help_text='The empty carton on its own.', max_digits=10, null=True, verbose_name='box weight (kg)')),
                ('packing_material_weight_kg', models.DecimalField(blank=True, decimal_places=3, help_text='Padding and filler inside the box, not the box itself.', max_digits=10, null=True, verbose_name='packing material weight (kg)')),
                ('style_no', models.CharField(help_text='Unique SKU code, e.g. DKC-TBL-OAK-01', max_length=64, unique=True)),
                ('description', models.CharField(help_text='Internal or trade name, e.g. Oak Dining Table', max_length=255)),
                ('customs_description', models.CharField(blank=True, help_text='Formal name for shipping documents; may differ from the description.', max_length=255)),
                ('hsn_code', models.CharField(blank=True, help_text='Harmonized System Nomenclature code.', max_length=20)),
                ('is_multi_part', models.BooleanField(default=False, help_text='On = ships disassembled in several cartons, one per part.')),
                ('is_fragile', models.BooleanField(default=False, help_text='Flags careful handling on documents.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('assembled_length_in', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='assembled length (in)')),
                ('assembled_width_in', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='assembled width (in)')),
                ('assembled_height_in', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='assembled height (in)')),
                ('assembled_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='assembled weight (kg)')),
                ('pack_per_box', models.PositiveIntegerField(default=1, help_text='Single-box products only: how many units fit in one carton.', validators=[django.core.validators.MinValueValidator(1)])),
                ('box_type', models.ForeignKey(blank=True, help_text='Picking a type fills the dimensions below; they stay editable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='masters.boxtype')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='masters.category')),
                ('product_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='masters.productgroup')),
            ],
            options={
                'ordering': ['style_no'],
            },
        ),
        migrations.CreateModel(
            name='ProductPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_length_in', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='box length (in)')),
                ('box_width_in', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='box width (in)')),
                ('box_height_in', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='box height (in)')),
                ('product_weight_kg', models.DecimalField(blank=True, decimal_places=3, help_text='The bare item with no packaging.', max_digits=10, null=True, verbose_name='product weight (kg)')),
                ('box_weight_kg', models.DecimalField(blank=True, decimal_places=3, help_text='The empty carton on its own.', max_digits=10, null=True, verbose_name='box weight (kg)')),
                ('packing_material_weight_kg', models.DecimalField(blank=True, decimal_places=3, help_text='Padding and filler inside the box, not the box itself.', max_digits=10, null=True, verbose_name='packing material weight (kg)')),
                ('name', models.CharField(help_text='e.g. Table top', max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('customs_description', models.CharField(blank=True, max_length=255)),
                ('hsn_code', models.CharField(blank=True, max_length=20)),
                ('length_in', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='part length (in)')),
                ('width_in', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='part width (in)')),
                ('height_in', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='part height (in)')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('box_type', models.ForeignKey(blank=True, help_text='Picking a type fills the dimensions below; they stay editable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='masters.boxtype')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='catalog.product')),
            ],
            options={
                'verbose_name': 'part',
                'ordering': ['product', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.catalog.models.product_image_path)),
                ('is_main', models.BooleanField(default=False, help_text='The one photo shown in lists and summaries.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.productpart')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('part__isnull', True), ('product__isnull', False)), models.Q(('part__isnull', False), ('product__isnull', True)), _connector='OR'), name='image_belongs_to_exactly_one_owner')],
            },
        ),
    ]
