# Generated by Django 5.2.8 on 2026-08-07 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='box_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_group',
        ),
        migrations.RemoveField(
            model_name='productpart',
            name='box_type',
        ),
    ]
