# Generated by Django 5.2.8 on 2026-08-07 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_product_box_type_remove_product_product_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-is_main', 'sort_order', 'id']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_fragile',
        ),
    ]
