# Generated by Django 5.2.8 on 2026-08-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_style_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_delegate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productpart',
            name='is_delegate',
            field=models.BooleanField(default=False),
        ),
    ]
