# Generated by Django 5.2.8 on 2026-09-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_is_delegate_productpart_is_delegate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hts_code',
            field=models.CharField(blank=True, help_text='US Harmonized Tariff Schedule code.', max_length=20),
        ),
        migrations.AddField(
            model_name='productpart',
            name='hts_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
